services:
    project-name-app:
        build: .
        container_name: laravel-app
        volumes:
            - .:/var/www
            - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - project-name-db
            - project-name-redis
        command: /bin/sh -c "while sleep 1000; do :; done"

    project-name-nginx:
        build: .docker/nginx
        container_name: laravel-nginx
        restart: always
        tty: true
        ports:
            - "8089:8088"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - project-name-app

    project-name-db:
        build: ./.docker/mysql
        container_name: laravel-db
        restart: always
        tty: true
        ports:
            - "33008:3308"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=project-name-db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    project-name-redis:
        image: redis:alpine
        container_name: laravel-redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
